language: c
dist: xenial

addons:
  apt:
    packages:
    - autoconf
    - automake
    - build-essential
    - git
    - gnulib
    - lcov
    - libcmocka-dev
    - libcurl4-openssl-dev
    - libprotobuf-dev
    - libssl-dev
    - libtool
    - ocaml
    - pkg-config
    - protobuf-compiler
    - python
    - sudo
    - wget

env:
  global:
  - JOBS="$(($(nproc)*3/2))"
  - PREFIX=/usr
  - MAKE="make --jobs=$JOBS"
  - ACLOCAL_DIR="/usr/share/gnulib/m4"

matrix:
  include:
  - compiler: clang
    env: SCANBUILD="scan-build --status-bugs" MAKE_TARGET=distcheck
  - compiler: gcc
    env: SCANBUILD= CONFIG_EXTRA="--enable-code-coverage" MAKE_TARGET=check

after_failure:
- cat tpm2-tcti-sgx-*/_build/sub/test-suite.log

after_success:
- |
  if [ ! -z "$COVERALLS_REPO_TOKEN" ] && [ "${CC}" = "gcc" ]; then
      coveralls --build-root=$(pwd) --exclude=./example --exclude=./test \
        --gcov-options '\-lp'
  fi

install:
- pip install --user cpp-coveralls
- .ci/build-deps.sh

before_script:
- source /opt/intel/sgxsdk/environment
- ./bootstrap

script:
- $SCANBUILD ./configure --enable-unit ${CONFIG_EXTRA}
- $SCANBUILD $MAKE $MAKE_TARGET
